### ISSUE TITLE
can't open device "/dev/ttyACM0": Device or resource busy

### ISSUE THREAD

**Issue by giobauermeister** [MediaTek-Labs/linkit-smart-7688-duo-arduino#5]
Every attempt to upload an Arduino Sketch to the Linkit 7688 Duo I get the error:

```
Arduino: 1.8.2 (Linux), Board: "LinkIt Smart 7688 Duo"

avrdude: ser_open(): can't open device "/dev/ttyACM0": Device or resource busy
```

Also when opening Serial monitor I get:

`Error opening serial port '/dev/ttyACM0'. (Port busy)`

I've already set up the permissions for ttyACM ports. For example, I can upload normally to an Arduino Leonardo which is also a Atmega32u4.

I always do my development stuff in Linux, don't wanna change to Windows just to use Linkit 7688 Duo.

Any ideas on how to solve this issue?

**Comment by giobauermeister** [comment]
Solved the issue either stopping modem manager or completely removing it.

`sudo stop modemmanager`

`sudo apt-get remove modemmanager`

**Comment by NonGrate** [comment]
The solution that always worked for me (for Arduino + ATMega328P) is to go to `Tools -> Port -> /dev/ttyACMx` and click the selected port again.

After that IDE uploads the code without a problem.

**Comment by surendra-realtime** [comment]
I guess you can use the following command from linux terminal:
$ fuser -k /dev/ttyACM0
user sudo (or su ) if required.

**Comment by cavoixanha** [comment]
You open serial editor of arduino can that problem!
